[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel"]
build-backend = 'setuptools.build_meta'

[tool.ruff]
select = [
  "E9", # syntax / io error
  "F63", # assertion traps
  "F7", # keyword outside special block
  "F82", # undefined variables
]